uploads = []
generated = []

[[outputs]]
id = "jPxBm29rGxS5Uw9TB9hig"
uri = "file://DEPLOY.md"
type = "text"
title = "Documentação Completa - Informe Centro-Oeste"

[[outputs]]
id = "0e--c3jAtmRO94seCveKZ"
uri = "file://noticias-sem-capa.md"
type = "text"
title = "Lista de notícias sem imagem de capa"
